### ISSUE TITLE
Exceptions thrown during exception serialization.

### ISSUE THREAD

**Issue by kbkk** [FriendsOfSymfony/FOSRestBundle#1814] opened 2017-12-09 09:55 UTC
I have two projects:

1.   - symfony 3.3.9
      - jms/serializer 1.8.1
      - jms/serializer-bundle  2.1.0
      - friendsofsymfony/rest-bundle 2.2.0 
2.   - symfony 4.0.1
      - jms/serializer 1.10.0
      - jms/serializer-bundle  2.3.1
      - friendsofsymfony/rest-bundle 2.3.0 

Example controller:
```
/**
  * @Route("/test")
  */
public function index()
{
    throw new \DomainException('an exception');
}
```

In the first project I get a proper response: `{"code":500,"message":"an exception"}`
However in the second one an exception is thrown: 
```

(2/2) RuntimeExceptionResources are not supported in serialized data. Path: Symfony\Component\HttpKernel\Log\Logger -> Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher -> ContainerOJzRqJn\srcDevDebugProjectContainer -> App\Auth\Controller\AuthController -> DomainException
--
in GraphNavigator.php (line 161)

```
I think in the first project FOS Rest Bundle used some kind of fallback when JMS could not serialize the exception (just my assumption). How to get the second project working properly?

**Comment by juliusstoerrle** [comment] 2017-12-09 11:36
The same as my last comment: https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1790

**Comment by juliusstoerrle** [comment] 2017-12-09 11:44
For Reference: https://github.com/schmittjoh/JMSSerializerBundle/issues/626#issuecomment-350439423

**Comment by juliusstoerrle** [comment] 2017-12-10 18:24
This should be solved by https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1805 (at least it works now on my side) @kbkk maybe you can test that commit so that @xabbuh can get the PR merged 

Here the Composer Version Constraint:  
`"friendsofsymfony/rest-bundle": "dev-master#dcd5add5153af7e479e97a233efa6fdcd0164879 as 2.3",
       `

**Comment by kbkk** [comment] 2017-12-10 19:38
@juliusstoerrle it did the trick. Why isn't it merged yet?

**Comment by juliusstoerrle** [comment] 2017-12-10 19:54
@kbkk Not sure, maybe @xabbuh wanted more feedback?

**Comment by xabbuh** [comment] 2017-12-10 20:12
Tests just don't pass yet as there are some more issues with the current implementation and I didn't find the time to finish it yet.

**Comment by jeff1985** [comment] 2018-02-08 18:58
Thanks for providing that issue! I also experienced the same. Fixed by switching to the dev version in composer.json:

    "friendsofsymfony/rest-bundle": "2.3.x-dev"

So imho the issue here can be closed as the issue is merged allready into master branch.

**Closed** 2018-11-26 17:44 UTC
