### ISSUE TITLE
Documentation brokeb

### ISSUE THREAD

**Issue by leberknecht** [FriendsOfSymfony/FOSRestBundle#948] opened 2015-01-26 19:12 UTC
Is it just me or are the links in the documentation broken @master atm?

https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Resources/doc/index.rst

**Comment by lsmith77** [comment] 2015-01-26 19:26
duplicate of https://github.com/FriendsOfSymfony/FOSRestBundle/issues/931

**Closed by lsmith77** 2015-01-26 19:26 UTC
