### ISSUE TITLE
[Routing] RESTFull using routing prefix method PUT

### ISSUE THREAD

**Issue by afranioce** [FriendsOfSymfony/FOSRestBundle#1010] opened 2015-04-11 18:13 UTC
I am using symfony version 2.6.6
```yaml
#src/Acme/Resources/config/routing.yml
acme_rest_api_profile:
    resource: "@Acme/Resources/config/routing/profile.yml"
    prefix:   /api/user/profile
```
Routing to profile, i'm taking the user by the session and does not need to pass the parameter.
```yaml
acme_rest_api_profile_show:
    path: /
    defaults: { _controller: RestAPIBundle:Profile:show, _format: ~ }
    requirements:
        _method: GET
acme_rest_api_profile_update:
    path: /
    defaults: { _controller: RestAPIBundle:Profile:edit, _format: ~ }
    requirements:
        _method: PUT
```
http://test.local/api/user/profile "No route found for "PUT /api/user/profile"
http://test.local/api/user/profile/ "Return success"

What am I doing something wrong?

**Comment by lsmith77** [comment] 2015-04-12 09:48
what do you get when you run: ``app/console router:debug | grep profile`` ?

**Comment by lsmith77** [comment] 2015-04-12 09:50
actually .. you do not seem to be using the route generation from this Bundle .. so the issue is probably not related to this Bundle at all but more a general Symfony2 routing issue.

**Comment by afranioce** [comment] 2015-04-13 12:15
to run: app/console router:debug | grep profile
```shell
...
rest_api_user_profile_show   GET         ANY    ANY  /api/user/profile/
rest_api_user_profile_update PUT         ANY    ANY  /api/user/profile/
...
```

**Comment by lsmith77** [comment] 2015-04-13 12:34
looks good and what about ``app/console router:debug rest_api_user_profile_update`` ?

but again, you are not using the RESTful route generation of this Bundle, you are just defining routes using the standard Symfony routing system

**Comment by afranioce** [comment] 2015-04-13 12:47
Would this, I should use it?

http://symfony.com/doc/current/bundles/FOSRestBundle/6-automatic-route-generation_multiple-restful-controllers.html

```php
//...
class ProfileController extends FOSRestController
{
    public function showAction()
    {
        //...
    } // "rest_user_profile_show"   [GET] /api/user/profile

    public function showAction()
    {
        //...
    } // "rest_user_profile_update"  [PUT] /api/user/profile
}
```

**Comment by lsmith77** [comment] 2015-04-16 09:36
@afranioce you can use it. there is nothing wrong with using the Symfony core routing and not relying on the route generation of this Bundle. its a question of preference. my point was just that if you are not using the route generation of this Bundle, then this is not the right place to find an answer.

**Comment by stof** [comment] 2015-04-18 10:51
You are not doing anything wrong with your route definition. But your route is defined as being ``/api/user/profile/``, so accessing ``/api/user/profile`` is not the same.
In case a route could match by adding a ``/`` at the end, Symfony redirects you to make the life easier for clients. But it does that only for safe requests (i.e. GET and HEAD), because redirecting other methods is not supported properly by browsers (they will generally follow the redirection with a GET request). So the solution is simple: use the URL you defined in your routing files, not a different one.

Anyway, I'm closing this issue because there is nothing related to FOSRestBundle in it.

**Closed by stof** 2015-04-18 10:51 UTC
