### ISSUE TITLE
Not compatible with _error route in symfony 2.7+

### ISSUE THREAD

**Issue by lyrixx** [FriendsOfSymfony/FOSRestBundle#1237] opened 2015-11-30 12:46 UTC
I have tested it with symfony 2.7 and symfony 2.8 and both generate the same error.
How to reproduce:

* `symfony new sf-error-fosrest 2.8` (2.7 is affected too)
* install jms serializer
* install fos rest
* enable body converter:
```
# config.yml
fos_rest:
    body_converter:
        enabled: true
```
* `app/console server:run`

Then go to http://127.0.0.1:8000/_error/404

![screenshot6](https://cloud.githubusercontent.com/assets/408368/11471885/bc328d92-9768-11e5-9943-d545e34a7507.png)

**Comment by Ener-Getick** [comment] 2015-11-30 13:25
This error is caused by the twig exception controller which requires the logger.
Only the RequestBodyParamConverter can support this class so it is executed but it wasn't expected to be...

I don't really see a solution to this problem except creating a list of the classes to ignore...

**Comment by lyrixx** [comment] 2015-11-30 13:37
I don't know fos rest at all, but I don't understand why fos rest try to do thing with constructor argument. It should deal only controller argument?

**Comment by Ener-Getick** [comment] 2015-11-30 13:41
FOSRestBundle tries to deal with [this class method](https://github.com/symfony/twig-bundle/blob/master/Controller/ExceptionController.php#L56) which requires the logger. This is not a constructor argument ;-)

**Comment by lyrixx** [comment] 2015-11-30 13:43
Oups, indeed. Sorry.

**Comment by Ener-Getick** [comment] 2015-11-30 14:26
We can also force the user to explicitly requests the ``RequestBodyParamConverter`` by checking that ``ParamConverter::getConverter() === 'fos_rest.request_body'`` but this is a BC break so only in 2.0...

**Comment by lyrixx** [comment] 2015-11-30 17:07
How can I work-arround it?

**Comment by Ener-Getick** [comment] 2015-11-30 17:10
What do you think about this @xabbuh @lsmith77 ?

**Comment by ogizanagi** [comment] 2015-11-30 17:30
@Ener-Getick : What about adding a check in the `supports` method for a list of approved paths from a new configuration parameter:

```yaml
fos_rest:
    body_converter:
        enabled: true
        paths:  ['^/'] # defaults 
```

By default, when enabled, the converter will be supported for every requests. Otherwise, it can be configured to include required paths (or can work with exclusions instead, or both).

It'll do the trick for FOSRestBundle  < 2.0, and could be removed in 2.0 in favor of explicitly requesting the converter on the controller.

**Comment by Ener-Getick** [comment] 2015-11-30 17:45
Sure @ogizanagi, @lsmith77 introduced a similar feature in #1139 which was merged on master.
There are several BC breaks but I think that they can be easily removed to merged this PR in 1.* but it would mean to create a new 1.8 release.

#1152 tried to introduce something really flexible but @lsmith77 couldn't finish it if someone wants to continue the work on it, any help is welcome ;-)

**Comment by lsmith77** [comment] 2016-02-08 13:52
ping

**Closed** 2016-03-03 16:30 UTC
Labels: Bug, in review, Status: Needs Review
