### ISSUE TITLE
Access denied on GET method with no visible reason only in production mode

### ISSUE THREAD

**Issue by abimelex** [FriendsOfSymfony/FOSRestBundle#1541] opened 2016-07-19 11:45 UTC
When I'm in production mode I got the following access denied error for all my GET requests, but only in production mode and only for one bundle. I can't find the reason for this I also loaded the same configs as in dev mode.

POST and PATCH requests works. DELETE is also forbidden...

FOS REST Bundle: v1.7.4
Symfony: v2.6.12

`request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "You do not have the necessary permissions" at /var/www/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/AccessDeniedListener.php line 70 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): You do not have the necessary permissions at /var/www/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/AccessDeniedListener.php:70, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /var/www/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []`

**Comment by lsmith77** [comment] 2016-07-22 12:16
the cause for this does not need to be in FOSRestBundle. AccessDeniedListener is simply triggered because there is an uncaught ``AccessDeniedException``.

**Comment by abimelex** [comment] 2016-07-22 12:21
I couldn't found the reason for this, but I removed FOSrest from the controller and now it works.

**Comment by xabbuh** [comment] 2016-10-14 09:26
Closing as the problem seems to have been solved.

@abimelex Please let us know if you think that we still need to fix something.

**Closed by xabbuh** 2016-10-14 09:26 UTC

**Comment by NileshHake** [comment] 2019-10-01 17:56
Hi All,

I am using restfull api I have getting  same error, please find my below fos_rest config deatil and log for the file 

Rest configuration:

**fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
        - { priorities: ['json', 'html', '*/*'], fallback_format: json, prefer_extension: true }
    view:
        view_response_listener: 'force'
    access_denied_listener:
        json: true
    service:
        serializer: jms_serializer.serializer
        view_handler: fos_rest.view_handler.default**

Below is the log file for same: 

**[2019-10-01 13:39:31] request.INFO: Matched route "dashboard_index" (parameters: "_controller": "Dermwrite\DashboardBundle\Controller\DefaultController::indexAction", "_route": "dashboard_index") [] []
[2019-10-01 13:39:31] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2019-10-01 13:39:31] security.INFO: No expression found; abstaining from voting. [] []
[2019-10-01 13:39:31] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "You do not have the necessary permissions" at /var/www/com-dermwrite/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/AccessDeniedListener.php line 70 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): You do not have the necessary permissions at /var/www/com-dermwrite/vendor/friendsofsymfony/rest-bundle/FOS/RestBundle/EventListener/AccessDeniedListener.php:70, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied at /var/www/com-dermwrite/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"} []
[2019-10-01 13:39:31] security.INFO: No expression found; abstaining from voting. [] []
[2019-10-01 13:39:31] event.DEBUG: Notified event "kernel.request" to listener "Symfony\Component\EventDispatcher\Debug\WrappedListener::__invoke". [] []**
