### ISSUE TITLE
Issue with JMSSerializer and param enable_short_alias: false 

### ISSUE THREAD

**Issue by Yoann53** [FriendsOfSymfony/FOSRestBundle#1627] opened 2016-12-06 09:49 UTC
I use Symfony\serializer with custom Normalizers. So I setted enable_short_alias to false in JMS Serializer params in my config.yml
But when I want to use JMS Serializer, I obtain the following exception :
Catchable Fatal Error: Argument 1 passed to App\\HttpFoundation\\ControllerResultConverter\\NullResult::__construct() must implement interface JMS\\Serializer\\SerializerInterface, instance of Symfony\\Component\\Serializer\\Serializer given, called in /Foo/var/cache/dev/appDevDebugProjectContainer.php on line 696 and defined".

I tried to understand how code works, and tried to specified jms_serializer as service in config.yml globally for fos_rest_bundle and next as the serializer service for param_fetcher_listener but it expected a FOS\RestBundle\Serializer\Serializer object. 

There is a JMSSerializerAdapter in the bundle and service to use it finally, I tried to force them to use jms_serializer service but it doesn't work.

I think I miss something but I don't know what, could you explain me how to proceed ?

**Comment by xabbuh** [comment] 2016-12-09 12:04
Can you show the stack trace of this error? Is it happening when FOSRestBundle tries to serialise stuff or when you are doing some custom serialisation?

**Comment by Yoann53** [comment] 2016-12-12 14:05
Yes, sorry :

{
  "error": {
    "code": 500,
    "message": "Internal Server Error",
    "exception": [
      {
        "message": "Catchable Fatal Error: Argument 1 passed to App\\HttpFoundation\\ControllerResultConverter\\NullResult::__construct() must implement interface JMS\\Serializer\\SerializerInterface, instance of Symfony\\Component\\Serializer\\Serializer given, called in /Applications/MAMP/htdocs/MoovTime-V2/var/cache/dev/appDevDebugProjectContainer.php on line 696 and defined",
        "class": "Symfony\\Component\\Debug\\Exception\\ContextErrorException",
        "trace": [
          {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "/Applications/MAMP/htdocs/MoovTime-V2/src/App/HttpFoundation/ControllerResultConverter/NullResult.php",
            "line": 15,
            "args": []
          },
          {
            "namespace": "Symfony\\Component\\Debug",
            "short_class": "ErrorHandler",
            "class": "Symfony\\Component\\Debug\\ErrorHandler",
            "type": "->",
            "function": "handleError",
            "file": "/Applications/MAMP/htdocs/MoovTime-V2/src/App/HttpFoundation/ControllerResultConverter/NullResult.php",
            "line": 15,
            "args": [
              [
                "string",
                "4096"
              ],
              [
                "string",
                "Argument 1 passed to App\\HttpFoundation\\ControllerResultConverter\\NullResult::__construct() must implement interface JMS\\Serializer\\SerializerInterface, instance of Symfony\\Component\\Serializer\\Serializer given, called in /Applications/MAMP/htdocs/MoovTime-V2/var/cache/dev/appDevDebugProjectContainer.php on line 696 and defined"
              ],
              [
                "string",
                "/Applications/MAMP/htdocs/MoovTime-V2/src/App/HttpFoundation/ControllerResultConverter/NullResult.php"
              ],
              [
                "string",
                "15"
              ],
              [
                "array",
                []
              ]
            ]
          },
          {
            "namespace": "App\\HttpFoundation\\ControllerResultConverter",
            "short_class": "NullResult",
            "class": "App\\HttpFoundation\\ControllerResultConverter\\NullResult",
            "type": "->",
            "function": "__construct",
            "file": "/Applications/MAMP/htdocs/MoovTime-V2/var/cache/dev/appDevDebugProjectContainer.php",
            "line": 696,
            "args": [
              [
                "object",
                "Symfony\\Component\\Serializer\\Serializer"
              ]
            ]
          },
          {
            "namespace": "",
            "short_class": "appDevDebugProjectContainer",
            "class": "appDevDebugProjectContainer",
            "type": "->",
            "function": "getApp_EventListener_ViewService",
            "file": "/Applications/MAMP/htdocs/MoovTime-V2/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php",
            "line": 275,
            "args": []
          },
          {
            "namespace": "Symfony\\Component\\DependencyInjection",
            "short_class": "Container",
            "class": "Symfony\\Component\\DependencyInjection\\Container",
            "type": "->",
            "function": "get",
            "file": "/Applications/MAMP/htdocs/MoovTime-V2/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php",
            "line": 181,
            "args": [
              [
                "string",
                "app.event_listener.view"
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\EventDispatcher",
            "short_class": "ContainerAwareEventDispatcher",
            "class": "Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher",
            "type": "->",
            "function": "lazyLoad",
            "file": "/Applications/MAMP/htdocs/MoovTime-V2/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php",
            "line": 127,
            "args": [
              [
                "string",
                "kernel.view"
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\EventDispatcher",
            "short_class": "ContainerAwareEventDispatcher",
            "class": "Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher",
            "type": "->",
            "function": "getListeners",
            "file": "/Applications/MAMP/htdocs/MoovTime-V2/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php",
            "line": 241,
            "args": [
              [
                "string",
                "kernel.view"
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
            "short_class": "TraceableEventDispatcher",
            "class": "Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher",
            "type": "->",
            "function": "preProcess",
            "file": "/Applications/MAMP/htdocs/MoovTime-V2/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php",
            "line": 131,
            "args": [
              [
                "string",
                "kernel.view"
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
            "short_class": "TraceableEventDispatcher",
            "class": "Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher",
            "type": "->",
            "function": "dispatch",
            "file": "/Applications/MAMP/htdocs/MoovTime-V2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php",
            "line": 149,
            "args": [
              [
                "string",
                "kernel.view"
              ],
              [
                "object",
                "Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent"
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\HttpKernel",
            "short_class": "HttpKernel",
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
            "type": "->",
            "function": "handleRaw",
            "file": "/Applications/MAMP/htdocs/MoovTime-V2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php",
            "line": 64,
            "args": [
              [
                "object",
                "Symfony\\Component\\HttpFoundation\\Request"
              ],
              [
                "string",
                "1"
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\HttpKernel",
            "short_class": "HttpKernel",
            "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
            "type": "->",
            "function": "handle",
            "file": "/Applications/MAMP/htdocs/MoovTime-V2/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php",
            "line": 169,
            "args": [
              [
                "object",
                "Symfony\\Component\\HttpFoundation\\Request"
              ],
              [
                "string",
                "1"
              ],
              [
                "boolean",
                true
              ]
            ]
          },
          {
            "namespace": "Symfony\\Component\\HttpKernel",
            "short_class": "Kernel",
            "class": "Symfony\\Component\\HttpKernel\\Kernel",
            "type": "->",
            "function": "handle",
            "file": "/Applications/MAMP/htdocs/MoovTime-V2/web/app_dev.php",
            "line": 11,
            "args": [
              [
                "object",
                "Symfony\\Component\\HttpFoundation\\Request"
              ]
            ]
          }
        ]
      }
    ]
  }
}


It is happening when FOSRestBundle tries to serialise stuff. When I use custom serialization, I use symfony serializer for the "normalize" method and that works with enable_short_alias to false.

**Comment by xabbuh** [comment] 2016-12-12 18:24
Thanks, could you also please show your FOSRestBundle configuration?

**Comment by GuilhemN** [comment] 2016-12-15 16:27
I wonder, isn't this related to https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1622 ?

**Comment by xabbuh** [comment] 2016-12-16 10:33
@GuilhemN Not completely sure, but it seems so.

**Comment by Yoann53** [comment] 2016-12-19 10:40
Sorry guys, I'm late with discussion, my FOSRestBundle configuration in my config.yml :

fos_rest:
    param_fetcher_listener: true

That's all.

**Comment by stof** [comment] 2016-12-19 11:27
@xabbuh we should reference the JMS serializer service using its canonical name ``jms_serializer`` rather than  its ``serializer`` alias, because more and more people are disabling the alias due to conflicts with the Serializer support in Symfony 2.8

**Comment by xabbuh** [comment] 2016-12-19 12:17
@stof That should be resolved by #1622.

**Comment by xabbuh** [comment] 2016-12-19 12:28
@Yoann53 Does #1622 fix your issue?

**Comment by Yoann53** [comment] 2016-12-19 14:27
No I always get the same trace, even with modifications of #1622

**Comment by GuilhemN** [comment] 2016-12-19 14:30
The error seems to be caused by your services configuration. Did you inject `@serializer` instead of `@jms_serializer.serializer` in `App\HttpFoundation\ControllerResultConverter\NullResult`?

**Comment by Yoann53** [comment] 2016-12-19 17:22
Well, that's works ! Sorry, I have not tried that. It's in the first file to see in the trace, I am feeling quiet stupid now :s, I need to inject @jms_serializer.serializer instead of @serializer in my Resources/config/services/http.yml in both services :

services:
    app.http_foundation.controller_result_converter.null_result:
        public: false
        class: App\HttpFoundation\ControllerResultConverter\NullResult
        arguments:
            - '@jms_serializer.serializer'

    app.http_foundation.controller_result_converter.last_modified_result:
        public: false
        class: App\HttpFoundation\ControllerResultConverter\LastModifiedResult

    app.http_foundation.controller_result_converter.serializable_result:
        public: false
        class: App\HttpFoundation\ControllerResultConverter\SerializableResult
        arguments:
            - '@jms_serializer.serializer'
            - '@security.token_storage'

I am working on an existing project. Could you confirm me HTTPFoundation directory is a manually added directory in my project or an added directory by fos_rest bundle installation ? In that case, I think it would be easier to use that feature if it is noted in the bundle documentation.

Thanks for your time.

**Comment by GuilhemN** [comment] 2016-12-19 17:36
No bundle I know adds stuff in your working directory (except for caching purpose), everything should be in `vendor`, so yes it's part of your project.

I close this as this is fixed :)

**Closed by GuilhemN** 2016-12-19 17:36 UTC

**Comment by Yoann53** [comment] 2016-12-19 17:59
Ok thanks !
