### ISSUE TITLE
Provided class "FOS\RestBundle\Serializer\JMSSerializerAdapter" is final and cannot be proxied

### ISSUE THREAD

**Issue by robhunt3r** [FriendsOfSymfony/FOSRestBundle#1325] opened 2016-01-25 08:30 UTC
Well, I just ran `composer update` and this exception is throwing.

`Provided class "FOS\RestBundle\Serializer\JMSSerializerAdapter" is final and cannot be proxied`

I've seen this exception is being thrown by https://github.com/Ocramius/ProxyManager but I can't go deeper because I don't know that much about this ProxyManager... I know Symfony uses it, but...

So project is dead until this gets fixed :8ball: I will do a rollback in my composer.

Okay, so I've just changed from `final class JMSSerializerAdapter` to `class`, and no errors are thrown. But this is not a fix, only a temporary fix in order to get my project working again for a while...

I must say, I'm on brand `dev-master`

**Comment by phoenixgao** [comment] 2016-01-25 09:16
Well, I just ran `composer update` too, and I am also looking at this error.

**Comment by Ener-Getick** [comment] 2016-01-25 14:29
Can you create a pr fixing this issue please? (just remove the final state)

**Comment by stof** [comment] 2016-01-25 18:33
The issue is related to the fact that the adapter classes are final, while the service definitions are marked as lazy.

**Comment by antkowiakit** [comment] 2016-01-26 08:20
I have this same issue. Temporary fix: `"friendsofsymfony/rest-bundle": "dev-master#46f70fa927b4e7aafbab8cf2d381f6f406f699a9"` in your composer.json

**Comment by robhunt3r** [comment] 2016-01-26 10:42
@antkowiakit There's a pull request fixing this.

https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1327

Also, @Ener-Getick could you check if it's working?

@stof So, the PR fix is not valid?

**Comment by Ener-Getick** [comment] 2016-01-26 19:48
@robhunt3r it's the correct fix if we want to let this services lazy and I think there is no enough advantages to let them final instead.

**Comment by Ener-Getick** [comment] 2016-01-27 14:43
Fixed in #1334

**Closed by Ener-Getick** 2016-01-27 14:43 UTC
