### ISSUE TITLE
NelmioApiDoc can not generate documentation

### ISSUE THREAD

**Issue by cedricduffournet** [FriendsOfSymfony/FOSRestBundle#1218] opened 2015-11-19 14:35 UTC
Since  AbstractScalarParameter::$array as been renamed to  ::$map, NelmioApiDoc can not generate documentation anymore.

Should I add an issue on NelmioApiDoc repository ?

**Comment by Ener-Getick** [comment] 2015-11-19 14:45
I'll make a PR. But isn't NelmioApiDoc not compatible with FOSRestBundle 2.0?

**Comment by willdurand** [comment] 2015-11-19 14:46
It is not supported at least.

**Comment by cedricduffournet** [comment] 2015-11-19 14:48
Ok I didn't know, actually It was working on my project before the modification

**Comment by willdurand** [comment] 2015-11-19 14:50
Well, it should work I guess except for some edge cases just like this one. I did not test to be honest, but I'd be interested in bringing FOSRestBundle 2.0 support into NelmioApiDocBundle.

**Comment by Ener-Getick** [comment] 2015-11-23 17:56
The problem is that this parameter doesn't have the same meaning in 2.0.
It is renamed to ``map`` and means that the parameter value will be validated row per row...

I think that we should create a new ``type`` option that would be more powerful.

**Comment by Ener-Getick** [comment] 2015-12-05 18:38
This is fixed in ``NelmioApiDocBundle`` 2.11.

**Closed by Ener-Getick** 2015-12-05 18:38 UTC
Labels: verified
