### ISSUE TITLE
This bundle tries to deserialize PSR-7 response and fails

### ISSUE THREAD

**Issue by rbaarsma** [FriendsOfSymfony/FOSRestBundle#1979] opened 2019-01-17 18:32 UTC
I found this issue while working with another bundle (https://github.com/trikoder/oauth2-bundle/issues/19), but it seems the FOSRestBundle is the root cause

It seems that any PSR-7 response (specifically the `Zend\\Diactoros\\Response`) is being deserialized through the JMSSerializerAdapter, which fails. 

Possibly this could be fixed in the `jms/serializer` too and then no change would be needed in FOSRestBundle, but I've posted the issue here, since I think it incorrectly calls `serialize()` on PSR-7 Response objects when the jms serializer doesn't support them.

**Comment by xabbuh** [comment] 2019-01-17 21:13
Without knowing how your code looks like it's hard to tell what is going wrong here. Can you create a small example application that allows us to reproduce?

**Comment by Tobion** [comment] 2019-08-21 20:17
Closing due to missing feedback.

**Closed by Tobion** 2019-08-21 20:17 UTC
