### ISSUE TITLE
AbstractFOSRestController extends AbstractController - is deprecated since Symfony 4.2.

### ISSUE THREAD

**Issue by suprim1** [FriendsOfSymfony/FOSRestBundle#2169] opened 2020-04-23 04:23 UTC
PHP Deprecated: Auto-injection of the container for "Controller" is deprecated since Symfony 4.2. Configure it as a service instead. in /app/vendor/symfony/framework-bundle/Controller/ControllerResolver.php on line 64

**Comment by xabbuh** [comment] 2020-04-23 05:00
Can you please provide more details? What did you do to end up with this message? Could you provide a small example application that allows to reproduce this?

**Comment by suprim1** [comment] 2020-04-23 05:21
class Controller extends AbstractFOSRestController
{}

**Comment by xabbuh** [comment] 2020-04-23 06:30
I am sorry, but this is not enough to reproduce your issue. Please create a small example application.

**Comment by suprim1** [comment] 2020-04-24 04:57
an example is any controller inherited from AbstractFOSRestController
when the containers are not yet formed, a warning is issued

https://github.com/symfony/symfony/blob/4.3/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php#L64

**Comment by xabbuh** [comment] 2020-04-24 05:35
This looks like you then did not properly configure the services for your controllers. But as said before without knowing what you are actually doing it's hard to tell what is wrong here.

**Comment by alexander-schranz** [comment] 2020-04-27 11:13
@suprim1 I had lately in a normal AbstractController the same problem that the container was not correctly injected when using a `alias` on a `service` and the service was not public maybe you did run into that issue: https://github.com/symfony/symfony/issues/36495 and did forget to make the service public.

**Comment by xabbuh** [comment] 2020-05-07 06:04
I am closing here since as I said before I do not think that's a FOSRestBundle related issue. We can still reopen in the future once we have a small example application that allows to reproduce.

**Closed by xabbuh** 2020-05-07 06:04 UTC
