### ISSUE TITLE
Custom MIME type and versioning cause failures

### ISSUE THREAD

**Issue by araines** [FriendsOfSymfony/FOSRestBundle#1399] opened 2016-03-21 18:04 UTC
FOSRestBundle 2.0 Beta 2
Symfony 2.7

I'm trying to implement a custom MIME type on my API, and require all clients to use it.  This part appears to work fine until I start to try to add versioning.

**config.yml**

```
fos_rest:
    view:
        view_response_listener: force
        mime_types:
            json: ['application/vnd.foo.api+json;version=3']
    versioning:
        enabled: true
        resolvers:
            media_type:
                enabled: true
                regex: '/version=(?P<version>[0-9]+)/'
    format_listener:
        enabled: true
        rules:
            -
                path: '^/bracket/'
                priorities: ['json']
                fallback_format: ~
                prefer_extension: false
```

When I send a request, I get a HTTP406 (Not Acceptable) response:

```
curl -H 'Accept: application/vnd.foo.api+json;version=3' http://localhost:8080/bar/20
```

Individually, both of these features appear to work.  For example, if I change my mime type as follows:

```
        mime_types:
            json: ['application/json;version=3']
```

And send a request:

```
curl -H 'Accept: application/json;version=3' http://localhost:8080/bar/20
```

Then I get the response I expect.

Also if I set it to my custom vendor descriptor:

```
        mime_types:
            json: ['application/vnd.foo.api+json;version=3']

curl -H 'Accept: application/vnd.foo.api+json' http://localhost:8080/bar/20
```

This also works (I get a HTTP200 response).

**Comment by Ener-Getick** [comment] 2016-03-21 19:26
Hum there are apparently 2 bugs in cause. 
The first one is in FOSRestBundle and is fixed by #1400 but the second one is caused by the symfony Request which removes all the parameters from the mime types (see [here](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php#L1349-L1351)).

So until a fix is applied on symfony you have to use this in your config:
```yml
mime_types:
    json: ['application/vnd.foo.api+json;version=3', 'application/vnd.foo.api+json']
```

**Comment by Ener-Getick** [comment] 2016-03-22 13:24
See https://github.com/symfony/symfony/pull/18255

**Comment by araines** [comment] 2016-03-23 15:53
@Ener-Getick appreciate the speedy and detailed response :)  Hopefully everything will get sorted at both ends soon!

**Comment by Ener-Getick** [comment] 2016-03-23 20:18
@araines thank you for your report, we need people like you to tell us when some features break :-)
https://github.com/symfony/symfony/pull/18255 doesn't contain major changes so this should be merged quickly.

**Comment by Ener-Getick** [comment] 2016-03-25 16:29
Fixed in https://github.com/symfony/symfony/pull/18255, you'll be able to use this fix as soon as patch versions are released ;-)

**Closed by Ener-Getick** 2016-03-25 16:29 UTC
Labels: in review
