### ISSUE TITLE
[BUG] Update from 1.4.2 to 1.5.3 illegal offset type in GenericMetadata.php

### ISSUE THREAD

**Issue by entering** [FriendsOfSymfony/FOSRestBundle#973] opened 2015-02-20 11:29 UTC
```
Warning: Illegal offset type in isset or empty in /vagrant/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/GenericMetadata.php line 216
500 Internal Server Error - ContextErrorException
```

symfony version: v2.5.3

The code:

```php
    /**
     * @QueryParam(
     *      name="letter",
     *      nullable=false,
     *      requirements="[A-Z\#]",
     *      default="A",
     *      strict=true,
     *      description="First letter of the Accommodation Provider's name to filter by"
     * )
     *
     * @param Request $request
     * @param string $letter
     *
     * @return Response
     */
    public function listAction(Request $request, $letter)
{
...
}
```

And the routing:
```yml
accommodation_provider_list:
    pattern:  /accommodation-providers
    defaults: { _controller: accommodation_bundle.accommodation_provider.controller:listAction }
    methods: [POST, GET]
```

**Comment by lsmith77** [comment] 2015-02-22 11:52
can you investigate this a but or submit a test a failing test case? there has been some refactoring in this area

**Comment by entering** [comment] 2015-02-22 12:09
@lsmith77 yes, I just opened the issue to avoid getting "lost", I will investigate and come at least with a failing test case

**Comment by lsmith77** [comment] 2015-03-26 10:13
ping

**Comment by lsmith77** [comment] 2015-04-03 16:11
did you also open a ticket on Symfony core?

/cc @webmozart

**Comment by mlimaloureiro** [comment] 2015-04-03 16:24
hello, i was investigating a little bit this issue, and the problem is with symfony LegacyValidator. Somehow, it is expecting an object instead of a value. Anyway this is fixed in 2.5.10, didn't investigate any further since updating symfony fixed the problem

**Comment by lsmith77** [comment] 2015-04-10 07:05
maybe it was fixed by https://github.com/symfony/Validator/commit/b90adb60265bec674a0a5ac12bff95d93f7d78f1

I guess then we could in theory add a conflict to lower versions. reading the commit info it would then be an issue with 2.5 versions up to exclusing 2.5.5. it never affected versions below 2.5 of course and also didn't affect 2.6 versions.

**Closed** 2015-04-10 12:57 UTC
Labels: ready
