### ISSUE TITLE
how to use uri versioning with a controller implementing the ClassResourceInterface?

### ISSUE THREAD

**Issue by roelleor** [FriendsOfSymfony/FOSRestBundle#1529] opened 2016-07-01 09:37 UTC
It doesn't seem possible to use uri versioning (/v1/users) with a controller implementing the ClassResourceInterface, is that correct? Or am I missing something?
route:

``` yml
users:
    type:     rest
    resource: AppBundle\Controller\UserController
    #prefix: {version} // doesn't work
```

**Comment by Ener-Getick** [comment] 2016-07-01 11:16
This should works as expected. 
At first, you must uncomment the line ``prefix``.
Do you load this controller somewhere else ?

**Comment by roelleor** [comment] 2016-07-01 11:29
Nope, not loading the controller somewhere else.
My config:
```yml
fos_rest:
    routing_loader:
        default_format: json
    format_listener:
        enabled: true
    versioning:
        enabled: true
    view:
        view_response_listener: force
        formats:
            json: true
            jsonp: false
            xml: false
            rss: false

```

**Comment by roelleor** [comment] 2016-07-01 11:38
to add: it does work well when using the version as a parameter

**Comment by Ener-Getick** [comment] 2016-07-01 12:04
In fact, you don't need the versioning feature of this bundle if you use a path parameter.
What do you mean by not working ? You can't access your  controller ?

**Comment by roelleor** [comment] 2016-07-01 12:09
it gives a "No route found” error
Perhaps you are right that one doesn’t strictly need it. One could just hard code the prefix. It’s not that much work, I’ll just go for that route then.
FYI, this approach of having {version} as a parameter in the path is in the documentation. However, not in combination with the ClassResourceInterface.

**Comment by tetele** [comment] 2016-07-27 18:15
Same issue here

    # app/config/routing.yml
    api:
        resource: "@ApiBundle/Resources/config/routes.yml"
        type:     rest
        prefix:   /api/{version}

and then

    # ApiBundle/Resources/config/routes.yml
    products:
        type:     rest
        resource: ApiBundle\Controller\ProductController
        name_prefix:  api_

    shops:
        type:     rest
        resource: ApiBundle\Controller\ShopController
        name_prefix:  api_

When trying to access `/api/v1/shops`, a "no route found" exception is thrown. Note that this stopped working after I upgraded from `2.0.0-BETA` to `2.0.0`. Not to mention it's in the docs, like @roelleor said.

**Comment by Lumbendil** [comment] 2016-08-23 11:44
Bumping this issue, as it's happening to me aswell.

**Comment by Ener-Getick** [comment] 2016-08-23 11:51
Can you try finding the corresponding route with `bin/console debug:router` ?

**Comment by Lumbendil** [comment] 2016-08-23 12:21
@Ener-Getick 

    vagrant@mymachine:/vagrant$ app/console debug:router get_categories
    +--------------+--------------------------------------------------------------------+
    | Property     | Value                                                              |
    +--------------+--------------------------------------------------------------------+
    | Route Name   | get_categories                                                     |
    | Path         | /frontend/api/{tube}/{version}/categories                          |
    | Path Regex   | #^/frontend/api/(?P<tube>[^/]++)/(?P<version>[^/]++)/categories$#s |
    | Host         | ANY                                                                |
    | Host Regex   |                                                                    |
    | Scheme       | ANY                                                                |
    | Method       | GET                                                                |
    | Requirements | NO CUSTOM                                                          |
    | Class        | Symfony\Component\Routing\Route                                    |
    | Defaults     | _controller: ApiBundle:Frontend\V1\Category:cget                   |
    |              | _format: json                                                      |
    | Options      | compiler_class: Symfony\Component\Routing\RouteCompiler            |
    +--------------+--------------------------------------------------------------------+

Should be noted aswell that in the profiler the symfony matcher complains about `attributes.get('version')` not being equal to `v1` (my version).

**Comment by xabbuh** [comment] 2016-10-12 18:01
@Lumbendil What is the exact path that you are trying? What output do you get when using the `router:match` command with that path?

**Comment by Lumbendil** [comment] 2016-10-12 20:26
@xabbuh answer from memory.

The path I tried was `/frontend/api/something/v1/categories`, there was no match, and on symfony debug, when inspecting, it said something along "get_categories" route is a close match but version doesn't match the requirements (the route version was being overriden by the listener).

**Comment by Lumbendil** [comment] 2016-10-12 20:26
It should be noted that adding `?version=v1` did make the route match.

**Comment by hipio** [comment] 2016-12-22 11:09
I am sorry to bump this issue, but was this ever resolved as I am running into this problem myself? The reason this seems to go wrong is because the Request given to `RedirectableUrlMatcher` does not contain any attributes when accessing a route like `/api/{version}/emails` where `{version}` is `v1` (this can easily be tested by adding a function that outputs data, for example `var_dump`, calling `$request->attributes->get('version')`).

When I dump the Request I get in the controller `$request->attributes->get('version')` does return `v1`.

**Comment by xabbuh** [comment] 2016-12-22 11:13
If someone of you could provide a small project that makes it possible to reproduce your issue, we could look into where the issue actually lies and try to solve it. That would be great. :)

**Comment by hipio** [comment] 2016-12-22 11:14
@xabbuh I'll try to get a small example up and running after lunch. ;)

**Comment by hipio** [comment] 2016-12-22 11:35
@xabbuh Here you go: https://github.com/hipio/FosRestBundleFoc

**Comment by juillerat** [comment] 2016-12-27 14:05
The problem is linked with priority of kernel.request event listeners
- VersionListener ([onKernelRequest priority 33](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/3b57396858050569906794d60aafe8988b25c2b5/Resources/config/versioning.xml#L12)) will run before Symfony RouterListener ([kernel.request with priority 32](https://github.com/symfony/symfony/blob/d0e8476afcab2c27191b55bfb6e0424b86646575/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php#L136)). Then [`$request->attributes->get("version")`](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/3b57396858050569906794d60aafe8988b25c2b5/EventListener/VersionListener.php#L46) in VersionListener (priority 33) will never take into account the value of {version} url placeholder, as this will be defined later in Symfony RouterListener (priority 32).
- VersionListener has to be executed before RouterListener, as the latter will match requested version (parsed with on priority 33) with routes using conditions that have been defined with @Version annotation (matching occurring on priority 32).
- Even more subtle, as implemented now, @Version annotation cannot work with uri placeholders. In fact, @Version annotations define route conditions with expressions, using [`request.attributes.get('version') in [...]`](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/3b57396858050569906794d60aafe8988b25c2b5/Routing/Loader/Reader/RestActionReader.php#L352). These conditions are evaluated by Symfony RouterListener (priority 32), but at the time of evaluation, request.attributes.get('version') is still empty for url placeholders. The [RequestMatcherInterface](https://github.com/symfony/symfony/blob/d0e8476afcab2c27191b55bfb6e0424b86646575/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php#L100-L104) will throw a [ResourceNotFoundException](https://github.com/symfony/symfony/blob/d0e8476afcab2c27191b55bfb6e0424b86646575/src/Symfony/Component/Routing/Matcher/UrlMatcher.php#L96-L98) before the url placeholder value [is stored in request attributes](https://github.com/symfony/symfony/blob/d0e8476afcab2c27191b55bfb6e0424b86646575/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php#L115). This explain issue #1491

To resolve all these problems at the same time, I think we need to:
- keep VersionListener with priority of 33 to resolve all versions but uri {version} placeholder
- let Symfony RouterListener resolve uri {version} placeholder with priority of 32 and also match route requirements and conditions
- apply the version exclusion strategy once all versions possibilities are resolved. So delegate this exclusion to a kernel request listener with priority < 32)
- when a {version} placeholder is used in a path (prefix, path, route annotation, etc.), we should match routes by requirements and not conditions to fix issue #1491

I will propose a PR that fix issues #1491 and #1529

**Comment by crashev** [comment] 2017-07-26 15:27
Are there any workarounds for URI versioning? It still seems not to work, only query and header versioning works

**Comment by osavchenko** [comment] 2018-01-02 15:28
Yes, still not working URI versioning. Why it happens and how I can help to fix this (maybe, we need new resolver for this)?

**Comment by lgraubner** [comment] 2018-02-21 09:47
You can simply add your own `onKernelRequest` listener to work around the problem described by @juillerat.

```php
namespace AppBundle\EventListener;

use FOS\RestBundle\View\ConfigurableViewHandlerInterface;
use FOS\RestBundle\View\ViewHandlerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;

class VersionListener
{
    private $viewHandler;

    public function __construct(ViewHandlerInterface $viewHandler)
    {
        $this->viewHandler = $viewHandler;
    }

    private function resolveVersion(Request $request)
    {
        $version = $request->attributes->get('version');

        return is_scalar($version) ? $version : strval($version);
    }

    public function onKernelRequest(GetResponseEvent $event)
    {

        $request = $event->getRequest();
        $version = str_replace('v', '', $this->resolveVersion($request));

        $request->attributes->set('version', $version);

        if ($this->viewHandler instanceof ConfigurableViewHandlerInterface) {
            $this->viewHandler->setExclusionStrategyVersion($version);
        }
    }
}
```

```yaml
app.version_listener:
        class: Acme\AppBundle\EventListener\VersionListener
        tags:
          - { name: kernel.event_listener, event: kernel.request, priority: 30 }
```

**Comment by bilel-noomene** [comment] 2018-03-04 22:51
+1

**Comment by mhightower** [comment] 2018-03-27 21:51
Was this problem ever resolved? I'm running into the same issue as @roelleor. I'm going to try the workaround but would like to configure it as documented.

**Comment by guilemos** [comment] 2018-06-29 16:54
+1

**Comment by yeomi** [comment] 2018-08-16 00:48
+1

**Comment by a-menshchikov** [comment] 2018-08-31 23:52
+1

**Comment by GuilhemN** [comment] 2018-09-13 20:44
Fixed in https://github.com/FriendsOfSymfony/FOSRestBundle/pull/1937 🎉

**Closed by GuilhemN** 2018-09-13 20:44 UTC
