### ISSUE TITLE
Symfony 4.4 controller_name_converter deprecation

### ISSUE THREAD

**Issue by Josee9988** [FriendsOfSymfony/FOSRestBundle#2057] opened 2020-01-25 13:44 UTC
When I run: 
```bash
php bin/console debug:config fos_rest
```
It gives me: 
```bash
2020-01-25T13:43:03+00:00 [info] User Deprecated: The "controller_name_converter" service is deprecated since Symfony 4.3. It is being referenced by the "fos_rest.routing.loader.controller" service.
```

I know there are other issues with a similar output but what is the way to fix this, if it is a problem

**Comment by tjveldhuizen** [comment] 2020-02-01 08:53
Duplicate of #2030 and #2059. See #2032 and #2036

**Comment by xabbuh** [comment] 2020-02-02 16:43
#2074 will fix this

**Comment by pejkosz94** [comment] 2020-02-04 07:13
@xabbuh when #2074 will be merged?

**Closed** 2020-02-04 09:03 UTC
