### ISSUE TITLE
Extend param fetcher by get<type> methods

### ISSUE THREAD

**Issue by kufd** [FriendsOfSymfony/FOSRestBundle#1787] opened 2017-11-15 18:51 UTC
Hi
I think it would be usefull to have in ParamFetcher methonds like:
getInt
getFloat
getBool
getString
When you expect that parameter has specific type

I can add them and provide pull request if you agree that it is usefull

**Comment by Tobion** [comment] 2020-04-19 14:39
Closing as duplicate of #1921

**Closed by Tobion** 2020-04-19 14:39 UTC
